sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: DPRdF7ZzEAVgXELGOpsP+XSRSPo5FeO3WgfJVV5fEUWt4cH8NmUthhkwKMR3X2UkeQ+S/193Muvmgc/kBfNNQvxwi1W09CbJdbtKWn+oxKTr0SIFkicGMEl8mLKwIpo1Am5+BjlfZHxb587zmkC+Pwc76QzTDMrhgfQqWrKJgdpTsvkH57xf7JSrQFeWWRRHRPCWgKpVp9ZIcjovYBmSF/NaI1kCLpzZyB2pZDR3r8mAgYCJvpijU3A/0fMnRAuTBeQ8pqV9RrUqKdSU99goLEPK1CivSMiYz3vPKzjPMDrHypaeoaswOBBI/UDg9Vnw9gLLv3sdKQl7MEdvDnRJF46KWCGiiEFKqgWqSPHNaP+vHRNASSZ78RxS51qji/nU5n/G9pAdY9Sx4+7VxWixlo918new+B4jvRCPHVnmMUPqNo6OpTdhqD5IIAm8BcdsEaboYafxfp6v5SjSBbcuSsZFYXSocsjyJvk5em94PtvbtOqs+xcI5dV9NObgs0973VIiRy/BMnXLVOSHSZpPGcwjiTyxBnemTkpDKM4foVAsUXP7tEEH64pm7RJZSjThs+tIh9+6FLYdlx8L3nJBgRVoKveZzYbvLyeKogZTceab/NIEl3eCaEuxMuYbmPt1yGxcNvy88y2jEDM+OLMSLHWQXrrpeW7GTkmMvH85yS4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Complete-Works-of-Artemus-Ward-Part-1-Essays-Sketches-and-Letters_3271
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy